### ISSUE TITLE
Error 2144-0001

### ISSUE THREAD

**Issue by Wasawala** [darkxex/CuteManga#3]
I have this crash error opening the app in applet mode. If i try to open it in homebrew menu after pressing R during game launch, the game closes instantly. I believe this is due to the lack of updates the app got and is outdated, making it unusable.
The crash report will be uploaded so you can read it.

[01624999990_0100000000001000.log](https://github.com/darkxex/CuteManga/files/6736402/01624999990_0100000000001000.log)

**Comment by darkxex** [comment]
Revisa los fork de github, ahí hay una versión actualizada.

**Comment by Wasawala** [comment]
The same thing happens with the last version
