### ISSUE TITLE
Pages are diplayed by date created, not filename

### ISSUE THREAD

**Issue by Aimela** [darkxex/CuteManga#7]
So, I saw this app and decided to try it out recently. Only, I found that the pages don't display in order. For example, a 6 page comic would display in the order of 1, 6, 2, 4, 3, 5; regardless of how I renamed the files. After some messing around on my own, I found the pages are in the order of the creation date of the files, rather than the filename.

This is a very strange way of displaying the pages, and I can only see it working if you're very careful about how you transfer the files. I haven't seen any page sorting options, so I think I'll have to wait for this to be changed to reasonably use the app.

**Comment by darkxex** [comment]
If I'm not mistaken, you must list them in 3 digits, example ... 001 002 003 004 005 006

**Comment by Aimela** [comment]
Did that, still displaying by file creation date.

**Comment by darkxex** [comment]
i understand, i will try fix this.

**Comment by darkxex** [comment]
could you upload your comic in a zip for download?

**Comment by darkxex** [comment]
@Aimela could you try with this version? https://github.com/darkxex/CuteManga/releases/tag/1.0.3
I just applied a sort to the vector containing the pages, I haven't tested it.

**Comment by Aimela** [comment]
Alight, all seems to be good now. I appreciate the promptness.

**Comment by darkxex** [comment]
ok.
